### ISSUE TITLE
Do refresh in background

### ISSUE THREAD

**Issue by samosfator** [samosfator/MODULE.OK#7]
Currently refreshing is in main UI thread. Need to move it to background thread in order to get rid of freezing the UI.

**Comment by samosfator** [comment]
No. It is because of blocking a main (UI) thread by `AsyncTask#get()`

**Comment by Filutkie** [comment]
_> wont fix_
_> **effect** of doing something important_
_> freezing the **ui** thread_

Wtf? Why wouldn't you just fix this issue? It is a bad practice. The Refresh button is **unresponsive** for now.

**Comment by samosfator** [comment]
@Filutkie Thanks for motivation. I was sure in complexity of this task and wrote that flimsy pretext to abandon the issue, but in fact the solution boiled down to some sort of callbacks. Fixed now.

**Comment by samosfator** [comment]
Due to migration to new JSON API this bug regressed again.
